"""Thai interface strings. Internal action identifiers stay language-neutral."""
TEXT = {
    "Jarvis • Personal assistant": "Jarvis • ผู้ช่วยส่วนตัว",
    "YOUR PERSONAL ASSISTANT": "ผู้ช่วยส่วนตัวของคุณ",
    "+  New conversation": "+  แชตใหม่",
    "Summarize text or file": "สรุปข้อความ / ไฟล์",
    "PC actions": "ควบคุมคอมพิวเตอร์",
    "AI settings": "ตั้งค่า AI และ API key",
    "HOW IT WORKS": "เริ่มใช้งาน",
    "1  Ask or dictate\n2  Review the suggestion\n3  Approve a PC action": "คุย  ·  สรุป  ·  ให้ช่วยทำงาน",
    "This session": "การเชื่อมต่อ",
    "AI key not connected": "ยังไม่ได้ตั้งค่า API key",
    "A little help. More headspace.": "แชตกับ Jarvis",
    "Stop": "หยุด",
    "Ready • Microphone off": "พร้อมใช้งาน • ไมโครโฟนปิด",
    "Review actions": "ตรวจสอบและอนุญาต",
    "Dictate": "พูดข้อความ",
    "Read reply": "อ่านคำตอบ",
    "Speak replies": "อ่านตอบอัตโนมัติ",
    "Send  ↗": "ส่ง  ↗",
    "Ctrl+Enter to send • Dictation inserts text for review • Esc stops speech and discards pending work": "Enter ส่ง  ·  Shift+Enter ขึ้นบรรทัดใหม่  ·  Esc หยุด",
    "Jarvis — AI settings": "Jarvis — ตั้งค่า AI",
    "Connect your AI": "ตั้งค่า AI",
    "Gemini API key": "Gemini API key",
    "Model ID": "ชื่อโมเดล",
    "Get an API key": "ขอ API key จาก Google",
    "Google data-use terms": "การใช้ข้อมูลของ Google",
    "Use these settings": "บันทึกการตั้งค่า",
    "Thinking with Gemini… • Microphone off": "Jarvis กำลังคิด… • ไมโครโฟนปิด",
    "Thinking with Gemini…": "Jarvis กำลังคิด…",
    "Dictation ready — review it and press Send • Microphone off": "ตรวจข้อความแล้วกดส่ง • ไมโครโฟนปิด",
    "No speech recognized • Try again or type your message": "ฟังไม่ชัด ลองอีกครั้งหรือพิมพ์ข้อความ",
    "Jarvis — approve one PC action": "Jarvis — ตรวจสอบการทำงาน",
    "Review before running": "ตรวจสอบก่อนให้ Jarvis ทำงาน",
    "Only this action will run. Cancel leaves your PC unchanged.": "อนุญาตเฉพาะรายการนี้ หรือกดยกเลิกได้",
    "Cancel": "ยกเลิก",
    "Approve this action": "อนุญาตให้ทำรายการนี้",
    "Jarvis — PC actions": "Jarvis — ควบคุมคอมพิวเตอร์",
    "Useful things, one click away": "ให้ Jarvis ช่วยทำงาน",
    "These work without an API key. Each opens an approval preview.": "คำสั่งด่วนใช้ได้โดยไม่ต้องมี API key",
    "Open Calculator": "เปิดเครื่องคิดเลข",
    "Open Notepad": "เปิด Notepad",
    "Open Downloads": "เปิดโฟลเดอร์ดาวน์โหลด",
    "Play / pause media": "เล่น / หยุดเพลง",
    "Jarvis — summarize": "Jarvis — สรุปข้อความ",
    "Make the long version useful": "สรุปให้เข้าใจง่าย",
    "Paste text or choose a UTF-8 text file. Review what will be sent to Gemini.": "วางข้อความหรือเลือกไฟล์ แล้วตรวจเนื้อหาก่อนส่งให้ AI",
    "Choose text file": "เลือกไฟล์ข้อความ",
    "Send to Gemini & summarize": "ส่งให้ AI สรุป",
    "Stop dictation": "หยุดฟัง",
    "Listening locally… Speak one sentence • Nothing is sent until you press Send": "กำลังฟังในเครื่อง… พูดหนึ่งประโยค แล้วตรวจข้อความก่อนส่ง",
    "Speaking locally… • Press Stop to interrupt": "กำลังอ่านคำตอบ… กดหยุดเพื่อขัดจังหวะ",
    "Stopped • Microphone off": "หยุดแล้ว • ไมโครโฟนปิด",
    "A fresh conversation. What would you like to do?": "เริ่มแชตใหม่แล้ว วันนี้อยากให้ช่วยอะไร?",
    "Please review the proposed action below.": "ตรวจสอบรายการที่ Jarvis เสนอด้านล่างได้เลย",
    "Stopped waiting for this reply. A request already sent to Google may still finish and incur usage.": "หยุดรอคำตอบแล้ว แต่คำขอที่ส่งให้ Google ไปแล้วอาจยังมีค่าใช้จ่าย",
    "In chat, you can also ask to open an HTTPS website, search the web,\nadjust media volume or save a new note. Web search opens your\nbrowser; Jarvis does not read those search results.": "สั่งผ่านแชตให้เปิดเว็บไซต์ ค้นหา ปรับเสียง หรือจดบันทึกได้\nการค้นหาแบบด่วนจะเปิดผลลัพธ์ในเบราว์เซอร์",
    "The API rejected the request. Check the model and API key.": "Gemini ปฏิเสธคำขอ ตรวจสอบชื่อโมเดลและ API key",
    "The API key was rejected.": "API key ไม่ถูกต้อง",
    "API access denied. Check the key, project and region.": "ไม่มีสิทธิ์ใช้ API ตรวจสอบคีย์ โปรเจกต์ และภูมิภาค",
    "That model is unavailable. Choose a model available to your API project.": "ไม่พบโมเดลนี้ เลือกโมเดลอื่นในตั้งค่า AI",
    "API quota or rate limit reached. Check your Google AI Studio usage.": "ใช้โควตา Gemini ครบแล้ว ดูการใช้งานใน Google AI Studio",
    "Could not reach Gemini. Check your internet connection and try again.": "ติดต่อ Gemini ไม่ได้ ตรวจสอบอินเทอร์เน็ตแล้วลองใหม่",
    "Gemini is busy (HTTP {code}). Try again shortly or change the model in AI settings.": "เซิร์ฟเวอร์ Gemini ไม่ว่างตอนนี้ (HTTP {code}) ลองใหม่อีกสักครู่ หรือเปลี่ยนโมเดลในตั้งค่า AI",
    "Gemini is busy, retrying ({n}/{total})…": "Gemini ไม่ว่าง กำลังลองใหม่ ({n}/{total})…",
    "Gemini returned HTTP {code}. Try again later.": "Gemini ตอบกลับ HTTP {code} ลองใหม่ภายหลัง",
    "The AI response was incomplete or blocked. Try a shorter request.": "คำตอบจาก AI ไม่สมบูรณ์หรือถูกบล็อก ลองสั่งให้สั้นลง",
    "The AI response was incomplete or blocked.": "คำตอบจาก AI ไม่สมบูรณ์หรือถูกบล็อก",
    "The AI returned an invalid response. No PC actions were accepted.": "AI ตอบกลับผิดรูปแบบ ไม่มีการทำงานบนคอมพิวเตอร์",
    "The AI returned an invalid screen step. Nothing was clicked.": "AI ส่งขั้นตอนหน้าจอผิดรูปแบบ ไม่มีการคลิก",
    "An action proposal was blocked: summarization cannot control the PC.": "บล็อกคำสั่งแล้ว: โหมดสรุปข้อความควบคุมคอมพิวเตอร์ไม่ได้",
    "Unexpected API redirect blocked.": "บล็อกการเปลี่ยนเส้นทาง API ที่ไม่คาดคิด",
    "Enter a valid Gemini API key in AI settings.": "ใส่ Gemini API key ที่ถูกต้องในตั้งค่า AI",
    "Use a Gemini model ID, for example gemini-3.8-flash.": "ใส่ชื่อโมเดล Gemini เช่น gemini-3.8-flash",
    "API response was too large; nothing was executed.": "คำตอบจาก API ใหญ่เกินไป ไม่มีการทำงานใดๆ",
    "Gemini returned unreadable data.": "Gemini ส่งข้อมูลที่อ่านไม่ได้",
    "An unexpected request error occurred. Nothing was executed.": "เกิดข้อผิดพลาดที่ไม่คาดคิด ไม่มีการทำงานใดๆ",
    "Screen step failed. Nothing was clicked.": "ขั้นตอนหน้าจอล้มเหลว ไม่มีการคลิก",
    "API key": "API key",
    "Paste your Gemini API key here, not into chat.": "วาง Gemini API key ในช่องนี้ ไม่ใช่ในแชต",
    "Model": "ชื่อโมเดล",
    "Enter a Gemini model ID.": "ใส่ชื่อโมเดล Gemini",
    "Message too long": "ข้อความยาวเกินไป",
    "Please use at most {n:,} characters.": "ใช้ได้ไม่เกิน {n:,} ตัวอักษร",
    "Cannot read document": "อ่านไฟล์ไม่ได้",
    "Document too long": "เอกสารยาวเกินไป",
    "Use at most {n:,} characters. Select a smaller excerpt.": "ใช้ได้ไม่เกิน {n:,} ตัวอักษร เลือกเฉพาะบางส่วน",
    "Request in progress": "กำลังรอคำตอบอยู่",
    "Wait for the current reply or press Stop first.": "รอคำตอบก่อน หรือกดหยุดก่อน",
    "Choose text to summarize": "เลือกไฟล์ที่จะสรุป",
    "Text documents": "ไฟล์ข้อความ",
    "All files": "ทุกไฟล์",
    "Cancelled: ": "ยกเลิกแล้ว: ",
    "Action did not complete: ": "ทำรายการไม่สำเร็จ: ",
    "Summarize the text I selected ({n:,} characters).": "สรุปข้อความที่เลือก ({n:,} ตัวอักษร)",
    "Copied": "คัดลอกแล้ว",
    "Copy": "คัดลอก",
    "Menu": "เมนู",
    "Stop (Esc)": "หยุด (Esc)",
    "Float window": "ย่อเป็นหน้าต่างลอย",
    "Expand window": "ขยายหน้าต่าง",
    "Dictate / stop": "พูดข้อความ / หยุดฟัง",
    "Send (Enter)": "ส่ง (Enter)",
    "New conversation": "แชตใหม่",
    "Open program folder": "เปิดโฟลเดอร์โปรแกรม",
    "Chat stays in memory. Sent messages go to Gemini.": "แชตนี้เก็บในหน่วยความจำ\nข้อความที่ส่งจะไปยัง Gemini",
    "Chat stays in memory. Sent messages go to your AI provider.": "แชตนี้เก็บในหน่วยความจำ\nข้อความที่ส่งจะไปยังผู้ให้บริการ AI ที่เลือก",
    "Wake word": "คำเรียก “Jarvis”",
    "Enter sonnet, haiku, opus or a gemini-… model ID.": "ใส่ sonnet, haiku, opus หรือชื่อโมเดล gemini-…",
    "Chat history is saved on this PC.": "ประวัติแชตถูกบันทึกไว้ในเครื่องนี้",
    "Mentor mode (POSN)": "โหมดติวเตอร์ (สอวน.)",
    "Save to wiki?": "บันทึกลงวิกิไหม?",
    "This page already exists and will be replaced.": "หน้านี้มีอยู่แล้วและจะถูกแทนที่",
    "Saved to wiki: ": "บันทึกลงวิกิแล้ว: ",
    "Could not save to wiki: ": "บันทึกลงวิกิไม่สำเร็จ: ",
}


def tr(text):
    return TEXT.get(text, text)
